### PR TITLE
Update definitions list

### PR DESCRIPTION
**Pull request by GQuirino**
update list of domains
following [Public Suffix List](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat)

### CODE REVIEW

**Comment by weppos** [comment]
@GQuirino how did you update the list? Did you update it manually?

**Comment by GQuirino** [comment]
yes, i did it manually. there is another way to do it?

**Comment by weppos** [comment]
There is a rake task.
https://github.com/weppos/publicsuffix-ruby/blob/2803479f5a1eceec0f1416ea538aa0ca301b64e9/Rakefile#L39

**Comment by GQuirino** [comment]
@weppos now updated by task, thanks for the heads up.

**Pull request merged**
