### PR TITLE
Details and examples for official PublicSuffix algorithm change

### PR DESCRIPTION
**Pull request by trevorturk**
Re: https://github.com/weppos/publicsuffix-ruby/pull/108#issuecomment-226246111

Please let me know if you'd like the monkey patch example removed, or you can merge and tweak as you see fit. Thank you!

### CODE REVIEW

**Comment by weppos** [comment]
Instead of monkey patching, I'd encourage people to create a custom wrapper (or proxy). That's for example what we do at DNSimple for third party libs.
http://confreaks.tv/videos/railsconf2016-developing-and-maintaining-a-platform-with-rails-and-lotus

It works very well, and you avoid monkey patching a lib you have no control of (that could more or less suddenly change).

**Comment by trevorturk** [comment]
Ok, I'll look into that. PR updated to remove the monkey patch example.

**Comment by trevorturk** [comment]
I don't think I caused that CI failure -- this patch is just a doc change.

**Comment by weppos** [comment]
It was definitely not you! Thanks for the patch.

**Pull request merged**
