### PR TITLE
revert to 5.0.5

### PR DESCRIPTION
**Pull request by nikita-nikolajev**
Ruby version upgrade is not a minor version upgrade of the package.
We have a dependency <6 on this package which causes all tools to fail because 5.0.5 was using Ruby 2* and 5.1.0 is using 3*
Please revert the change or release 5.1.1 that is still using Ruby 2* and rerelease 5.1.0 as version 6

### CODE REVIEW

**Comment by nikita-nikolajev** [comment]
I ran the following to revert it
git reset a8ffde7

**Comment by weppos** [comment]
Fixed in https://github.com/weppos/publicsuffix-ruby/commit/ae7839d351e63897eba8e1848ee42f271396383c and https://github.com/weppos/publicsuffix-ruby/commit/744ad67267f31a678626a0267b7b58c24f308bc7

**Comment by dentarg** [comment]
@nikita-nikolajev are you not using rubygems/bundler?

the gemspec was updated to indicate 3.0 or above in https://github.com/weppos/publicsuffix-ruby/commit/3496a44493ed2944fbcea9b68f93b46471989682

IMHO with that, libraries does not need to bump the major version when dropping older Ruby versions

**Comment by nikita-nikolajev** [comment]
bundler might be smart enough but gem install a package with public_suffix dependency <6 is not

**Comment by nikita-nikolajev** [comment]
we use bundler in dev/tst

**Comment by dentarg** [comment]
> bundler might be smart enough but gem install a package with public_suffix dependency <6 is not

I don't think that's true. See this comment for example https://github.com/rubygems/rubygems/issues/4521#issuecomment-817278653

**Comment by nikita-nikolajev** [comment]
> I don't think that's true. See this comment for example [rubygems/rubygems#4521 (comment)](https://github.com/rubygems/rubygems/issues/4521#issuecomment-817278653)
hmm, I am using ruby 2 so might be different. I should have run with --verbosity and --debug to see how exactly it tries to resolve the dependencies. Thanks for the link

**Comment by dentarg** [comment]
You may also find this thread interesting https://github.com/sporkmonger/addressable/issues/476

**Pull request closed without merging**
